# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    # - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  node1.organization1.example.com:
    container_name: node1.organization1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node1.organization1.example.com
      - CORE_PEER_ADDRESS=node1.organization1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node2.organization1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node1.organization1.example.com:7051
      - CORE_PEER_LOCALMSPID=organization1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization1.example.com/peers/node1.organization1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization1.example.com/peers/node1.organization1.example.com/tls:/etc/hyperledger/fabric/tls
        # - peer0.org1.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  node2.organization1.example.com:
    container_name: node2.organization1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node2.organization1.example.com
      - CORE_PEER_ADDRESS=node2.organization1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node2.organization1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node1.organization1.example.com:7051
      - CORE_PEER_LOCALMSPID=organization1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization1.example.com/peers/node2.organization1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization1.example.com/peers/node2.organization1.example.com/tls:/etc/hyperledger/fabric/tls
        # - peer1.org1.example.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  node1.organization2.example.com:
    container_name: node1.organization2.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node1.organization2.example.com
      - CORE_PEER_ADDRESS=node1.organization2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node1.organization2.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node2.organization2.example.com:7051
      - CORE_PEER_LOCALMSPID=organization2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization2.example.com/peers/node1.organization2.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization2.example.com/peers/node1.organization2.example.com/tls:/etc/hyperledger/fabric/tls
        # - peer0.org2.example.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  node2.organization2.example.com:
    container_name: node2.organization2.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node2.organization2.example.com
      - CORE_PEER_ADDRESS=node2.organization2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node2.organization2.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node1.organization2.example.com:7051
      - CORE_PEER_LOCALMSPID=organization2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization2.example.com/peers/node2.organization2.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization2.example.com/peers/node2.organization2.example.com/tls:/etc/hyperledger/fabric/tls
        # - peer1.org2.example.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  node1.organization3.example.com:
    container_name: node1.organization3.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node1.organization3.example.com
      - CORE_PEER_ADDRESS=node1.organization3.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node1.organization3.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node2.organization3.example.com:7051
      - CORE_PEER_LOCALMSPID=organization3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization3.example.com/peers/node1.organization3.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization3.example.com/peers/node1.organization3.example.com/tls:/etc/hyperledger/fabric/tls
        # - peer1.org2.example.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  node2.organization3.example.com:
    container_name: node2.organization3.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node2.organization3.example.com
      - CORE_PEER_ADDRESS=node2.organization3.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node2.organization3.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node1.organization3.example.com:7051
      - CORE_PEER_LOCALMSPID=organization3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization3.example.com/peers/node2.organization3.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization3.example.com/peers/node2.organization3.example.com/tls:/etc/hyperledger/fabric/tls
        # - peer1.org2.example.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
